### DISCUSSION TITLE
Deploy exporter to monitor multiple nginx-plus at once

### DISCUSSION THREAD

**Discussion by db-root** [nginx/nginx-prometheus-exporter#592] [Q&A]
The --nginx.scrape-uri parameter can be used to specify the api of nginx-plus that you need to monitor, so is it possible to deploy exporter on one server to monitor multiple nginx-plus with the --nginx.scrape-uri parameter? Has anyone ever tried it.

**Comment by lucacome** [comment]
Hi @db-root 

yes it's possible to specify the `--nginx.scrape-uri` paramter multiple times to monitor multiple NGINX Plus instances like

```
nginx-prometheus-exporter --nginx.scrape-uri http://server_one:8080/api --nginx.scrape-uri http://server_two:8080/api
```

**Reply by Skull0ne** [reply]
Hi

Jumping on that thread as I'm trying to do the same thing but I'm facing 2 issues : 
- metrics don't have a label with the scrape uri for example : 
`nginx_up{instance="nginx-exporter.prometheus:9113", job="nginx-exporter"}`
- when one of the targetted nginx is down, the exporter doesn't work anymore : logs say it can't reach my instance and it stops answering to curl even if the 2nd instance is up. I would have expected a nginx_up at 1 and another to 0

Here is my config (running the exporter as a deployment in kubernetes) : 
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        imagePullPolicy: Always
        image: nginx/nginx-prometheus-exporter:1.5.1
        ports:
        - containerPort: 9113
        args:
          - --nginx.scrape-uri=http://x.x.x.x:8080/nginx/status
          - --nginx.timeout=5s
          - --log.level=debug
          #- --nginx.scrape-uri=http://y.y.y.y:8080/nginx/status
```

Thanks
